Introduce a linter with a pre-commit hook
tokspace/tok-app pull request #5
Opened 2020-07-13 23:48 UTC by nchaloult

To enforce a consistent style guide throughout our project's source, this PR proposes to add [Prettier](https://prettier.io) along with [Husky](https://github.com/typicode/husky). Husky runs a linter over all changed/edited `.js` files once they reach `git`'s staging area.

Of course, the linter configs that I've included in `.prettierrc` are up for debate if you don't like something you see in there.

2020-07-13 23:50 UTC, akainth015 requested changes

2020-07-13 23:50 UTC, akainth015 commented on .prettierrc
> +  "tabWidth": 2,
Can we increase this to 4

2020-07-13 23:50 UTC, akainth015 commented on .prettierrc
> +  "singleQuote": true,
:angry:

2020-07-13 23:52 UTC, nchaloult commented on .prettierrc
> +  "tabWidth": 2,
sure! all done :)

2020-07-13 23:52 UTC, nchaloult commented on .prettierrc
> +  "singleQuote": true,
sure! all done :)

2020-07-13 23:53 UTC, akainth015 approved these changes
Looks good to me!

2020-07-13 23:53 UTC, yashika51 approved these changes

2020-07-14 00:12 UTC, jackyzha0 approved these changes
SPICY AF 😩 
L G T M

2020-07-14 00:12 UTC, merged